# Generated by Django 5.1.4 on 2024-12-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
